{
 "title": "TrueNAS Scale",
 "tags": [ "truenas" ],
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "job", "query": { "query": "label_values(uptime,job)" } },
   {
    "name": "hostname",
    "query": {
     "query": "label_values(uptime{job=\"$job\"},hostname)"
    }
   },
   {
    "name": "cpu",
    "query": {
     "query": "label_values(cpu_usage{hostname=\"$hostname\", job=\"$job\"},cpu)"
    }
   },
   {
    "name": "disk",
    "query": {
     "query": "label_values(disk_io{hostname=\"$hostname\", job=\"$job\"},disk)"
    }
   },
   {
    "name": "interface",
    "query": {
     "query": "label_values(interface_io{hostname=\"$hostname\", job=\"$job\"},interface)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "System load",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 6, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "system_load{hostname=~\"$hostname\"}",
     "legendFormat": "{{kind}}"
    }
   ]
  },
  {
   "title": "CPU frequency",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 6, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "rotmhz" } },
   "targets": [
    {
     "expr": "cpu_frequency{hostname=~\"$hostname\", cpu=~\"$cpu\"}",
     "legendFormat": "{{cpu}}"
    }
   ]
  },
  {
   "title": "CPU temperature",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 6, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "expr": "cpu_temperature{hostname=~\"$hostname\", cpu=~\"$cpu\"}",
     "legendFormat": "{{cpu}}"
    }
   ]
  },
  {
   "title": "Memory usage",
   "type": "piechart",
   "gridPos": { "h": 9, "w": 6, "x": 18, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "mbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "physical_memory{hostname=~\"$hostname\"}",
     "legendFormat": "{{kind}}"
    }
   ]
  },
  {
   "title": "Network I/O",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 6, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "Kbits" } },
   "targets": [
    {
     "expr": "interface_io{hostname=~\"$hostname\", interface=~\"$interface\"}",
     "legendFormat": "{{interface}} - {{op}}"
    }
   ]
  },
  {
   "title": "Pool State",
   "type": "state-timeline",
   "gridPos": { "h": 9, "w": 6, "x": 6, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "zfs_pool{hostname=~\"$hostname\"} > 0",
     "legendFormat": "{{pool}}"
    }
   ]
  },
  {
   "title": "Processes",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 6, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "processes{hostname=~\"$hostname\"}",
     "legendFormat": "{{kind}}"
    }
   ]
  },
  {
   "title": "Uptime",
   "type": "stat",
   "gridPos": { "h": 9, "w": 6, "x": 18, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "dtdhms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "uptime{hostname=~\"$hostname\"}",
     "legendFormat": "synced"
    }
   ]
  },
  {
   "title": "CPU",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 },
   "collapsed": true,
   "panels": [
    {
     "title": "CPU usage",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 6, "x": 0, "y": 19 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "cpu_total{hostname=~\"$hostname\"}",
       "legendFormat": "{{kind}}"
      }
     ]
    },
    {
     "title": "CPU frequency",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 6, "x": 6, "y": 19 },
     "fieldConfig": { "defaults": { "unit": "rotmhz" } },
     "targets": [
      {
       "expr": "cpu_frequency{hostname=~\"$hostname\", cpu=~\"$cpu\"}",
       "legendFormat": "{{cpu}}"
      }
     ]
    },
    {
     "title": "CPU temperature",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 6, "x": 12, "y": 19 },
     "fieldConfig": { "defaults": { "unit": "celsius" } },
     "targets": [
      {
       "expr": "cpu_temperature{hostname=~\"$hostname\", cpu=~\"$cpu\"}",
       "legendFormat": "{{cpu}}"
      }
     ]
    },
    {
     "title": "CPU C-State",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 6, "x": 18, "y": 19 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "avg by (state) (cpu_idlestate{hostname=~\"$hostname\", cpu=~\"$cpu\"})",
       "legendFormat": "{{state}}"
      }
     ]
    },
    {
     "title": "CPU throttling",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 6, "x": 0, "y": 28 },
     "fieldConfig": { "defaults": { "unit": "ops" } },
     "targets": [
      {
       "expr": "cpu_throttling{hostname=~\"$hostname\", cpu=~\"$cpu\"}",
       "legendFormat": "{{cpu}}"
      }
     ]
    },
    {
     "title": "Interrupts & Context switches",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 6, "x": 6, "y": 28 },
     "fieldConfig": { "defaults": { "unit": "ops" } },
     "targets": [
      {
       "expr": "interrupts{hostname=~\"$hostname\"}",
       "legendFormat": "{{kind}} - interrupt"
      },
      {
       "expr": "context_switches{hostname=~\"$hostname\"}",
       "legendFormat": "context switches"
      }
     ]
    }
   ]
  },
  {
   "title": "Memory",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 },
   "collapsed": true,
   "panels": [
    {
     "title": "Memory usage",
     "type": "piechart",
     "gridPos": { "h": 9, "w": 6, "x": 0, "y": 11 },
     "fieldConfig": { "defaults": { "unit": "mbytes" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "physical_memory{hostname=~\"$hostname\"}",
       "legendFormat": "{{kind}}"
      }
     ]
    },
    {
     "title": "Swap usage",
     "type": "piechart",
     "gridPos": { "h": 9, "w": 6, "x": 6, "y": 11 },
     "fieldConfig": { "defaults": { "unit": "mbytes" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "swap{hostname=~\"$hostname\"}",
       "legendFormat": "{{kind}}"
      }
     ]
    },
    {
     "title": "Memory detailed",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 6, "x": 12, "y": 11 },
     "fieldConfig": { "defaults": { "unit": "mbytes" } },
     "targets": [
      {
       "expr": "memory_available{hostname=~\"$hostname\"}",
       "legendFormat": "{{kind}}"
      },
      {
       "expr": "memory_committed{hostname=~\"$hostname\"}",
       "legendFormat": "{{kind}}"
      },
      {
       "expr": "memory_transparent_hugepages{hostname=~\"$hostname\"}",
       "legendFormat": "hugepages-{{kind}}"
      },
      {
       "expr": "memory_writeback{hostname=~\"$hostname\"}",
       "legendFormat": "writeback-{{kind}}"
      }
     ]
    },
    {
     "title": "Kernel memory allocation",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 6, "x": 18, "y": 11 },
     "fieldConfig": { "defaults": { "unit": "mbytes" } },
     "targets": [
      {
       "expr": "memory_kernel{hostname=~\"$hostname\"}",
       "legendFormat": "{{kind}}"
      }
     ]
    },
    {
     "title": "Memory slab",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 6, "x": 0, "y": 20 },
     "fieldConfig": { "defaults": { "unit": "mbytes" } },
     "targets": [
      {
       "expr": "memory_slab{hostname=~\"$hostname\"}",
       "legendFormat": "{{kind}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Network",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 20 },
   "collapsed": true,
   "panels": [
    {
     "title": "Network I/O",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 6, "x": 0, "y": 21 },
     "fieldConfig": { "defaults": { "unit": "Kbits" } },
     "targets": [
      {
       "expr": "interface_io{hostname=~\"$hostname\", interface=~\"$interface\"}",
       "legendFormat": "{{interface}} - {{op}}"
      }
     ]
    },
    {
     "title": "Interface speed",
     "type": "stat",
     "gridPos": { "h": 9, "w": 6, "x": 6, "y": 21 },
     "fieldConfig": { "defaults": { "unit": "Kbits" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "interface_speed{hostname=~\"$hostname\", interface=~\"$interface\"}",
       "legendFormat": "{{interface}}"
      }
     ]
    },
    {
     "title": "Interface duplex state",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 3, "x": 12, "y": 21 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "interface_duplex{hostname=~\"$hostname\", interface=~\"$interface\"} > 0",
       "legendFormat": "{{interface}} - {{state}}"
      }
     ]
    },
    {
     "title": "Interface operation state",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 3, "x": 15, "y": 21 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "interface_operationstate{hostname=~\"$hostname\", interface=~\"$interface\"} > 0",
       "legendFormat": "{{interface}} - {{state}}"
      }
     ]
    },
    {
     "title": "Interface carrier state",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 3, "x": 18, "y": 21 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "interface_carrierstate{hostname=~\"$hostname\", interface=~\"$interface\"} > 0",
       "legendFormat": "{{interface}} - {{state}}"
      }
     ]
    },
    {
     "title": "Interface MTU",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 3, "x": 21, "y": 21 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "interface_mtu{hostname=~\"$hostname\", interface=~\"$interface\"} > 0",
       "legendFormat": "{{interface}}"
      }
     ]
    },
    {
     "title": "Network packets",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 6, "x": 0, "y": 30 },
     "fieldConfig": { "defaults": { "unit": "pps" } },
     "targets": [
      {
       "expr": "interface_packets{hostname=~\"$hostname\", interface=~\"$interface\"}",
       "legendFormat": "{{interface}} - {{op}}"
      }
     ]
    },
    {
     "title": "Network errors & drops",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 6, "x": 6, "y": 30 },
     "fieldConfig": { "defaults": { "unit": "ops" } },
     "targets": [
      {
       "expr": "interface_errors{hostname=~\"$hostname\", interface=~\"$interface\"}",
       "legendFormat": "error ({{interface}} - {{op}})"
      },
      {
       "expr": "interface_drops{hostname=~\"$hostname\", interface=~\"$interface\"}",
       "legendFormat": "drop ({{interface}} - {{op}})"
      }
     ]
    }
   ]
  },
  {
   "title": "Processes",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 21 },
   "collapsed": true,
   "panels": [
    {
     "title": "Processes",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 6, "x": 0, "y": 22 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "processes{hostname=~\"$hostname\"}",
       "legendFormat": "{{kind}}"
      }
     ]
    },
    {
     "title": "Process forks",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 6, "x": 6, "y": 22 },
     "fieldConfig": { "defaults": { "unit": "ops" } },
     "targets": [
      {
       "expr": "processes_forks{hostname=~\"$hostname\"}",
       "legendFormat": "forks"
      }
     ]
    }
   ]
  },
  {
   "title": "Uptime + NTP",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 22 },
   "collapsed": true,
   "panels": [
    {
     "title": "Uptime",
     "type": "stat",
     "gridPos": { "h": 9, "w": 6, "x": 0, "y": 23 },
     "fieldConfig": { "defaults": { "unit": "dtdhms" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "uptime{hostname=~\"$hostname\"}",
       "legendFormat": "synced"
      }
     ]
    },
    {
     "title": "NTP synced",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 6, "x": 6, "y": 23 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "clock_synced{hostname=~\"$hostname\"}",
       "legendFormat": "synced"
      }
     ]
    },
    {
     "title": "NTP offset",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 6, "x": 12, "y": 23 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "clock_offset{hostname=~\"$hostname\"}",
       "legendFormat": "offset"
      }
     ]
    },
    {
     "title": "NTP error state",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 6, "x": 18, "y": 23 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "clock_status{hostname=~\"$hostname\"}",
       "legendFormat": "{{state}}"
      }
     ]
    }
   ]
  },
  {
   "title": "NFS",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 23 },
   "collapsed": true,
   "panels": [
    {
     "title": "NFS I/O",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 6, "x": 0, "y": 24 },
     "fieldConfig": { "defaults": { "unit": "KBs" } },
     "targets": [
      {
       "expr": "nfs_io{hostname=~\"$hostname\"}",
       "legendFormat": "{{op}}"
      }
     ]
    },
    {
     "title": "NFS net I/O",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 6, "x": 6, "y": 24 },
     "fieldConfig": { "defaults": { "unit": "pps" } },
     "targets": [
      {
       "expr": "nfs_net{hostname=~\"$hostname\"}",
       "legendFormat": "{{op}}"
      }
     ]
    },
    {
     "title": "NFS threads",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 6, "x": 12, "y": 24 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "nfs_threads{hostname=~\"$hostname\"}",
       "legendFormat": "threads"
      }
     ]
    },
    {
     "title": "NFS readcache",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 6, "x": 18, "y": 24 },
     "fieldConfig": { "defaults": { "unit": "rps" } },
     "targets": [
      {
       "expr": "nfs_readcache{hostname=~\"$hostname\"}",
       "legendFormat": "{{op}}"
      }
     ]
    },
    {
     "title": "NFS RPC",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 6, "x": 0, "y": 33 },
     "fieldConfig": { "defaults": { "unit": "ops" } },
     "targets": [
      {
       "expr": "nfs_rpc{hostname=~\"$hostname\"}",
       "legendFormat": "{{op}}"
      }
     ]
    },
    {
     "title": "NFS proc4",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 6, "x": 6, "y": 33 },
     "fieldConfig": { "defaults": { "unit": "ops" } },
     "targets": [
      {
       "expr": "nfs_proc4{hostname=~\"$hostname\"}",
       "legendFormat": "{{op}}"
      }
     ]
    },
    {
     "title": "NFS proc4ops",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 6, "x": 12, "y": 33 },
     "fieldConfig": { "defaults": { "unit": "ops" } },
     "targets": [
      {
       "expr": "nfs_proc4ops{hostname=~\"$hostname\"}",
       "legendFormat": "{{op}}"
      }
     ]
    }
   ]
  },
  { "title": "ZFS", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 24 } },
  {
   "title": "ARC Size",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 6, "x": 0, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "mbytes" } },
   "targets": [
    {
     "expr": "zfs_arc_size{hostname=~\"$hostname\", op=~\"arcsz|target\"}",
     "legendFormat": "{{op}}"
    }
   ]
  },
  {
   "title": "L2 Size",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 6, "x": 6, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "mbytes" } },
   "targets": [
    {
     "expr": "zfs_l2_size{hostname=~\"$hostname\"}",
     "legendFormat": "{{op}}"
    }
   ]
  },
  {
   "title": "ZFS reads",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 6, "x": 12, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "rps" } },
   "targets": [
    {
     "expr": "zfs_reads{hostname=~\"$hostname\"}",
     "legendFormat": "{{op}}"
    }
   ]
  },
  {
   "title": "ZFS cache access",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 6, "x": 18, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "zfs_hits{hostname=~\"$hostname\"}",
     "legendFormat": "{{op}}"
    }
   ]
  },
  {
   "title": "ARC Size Breakdown",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 6, "x": 0, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "zfs_arc_size_breakdown{hostname=~\"$hostname\"}",
     "legendFormat": "{{op}}"
    }
   ]
  },
  {
   "title": "ZFS hash elements",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 6, "x": 6, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "zfs_hash_elements{hostname=~\"$hostname\"}",
     "legendFormat": "hashes - {{op}}"
    }
   ]
  },
  {
   "title": "ZFS important operations",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 6, "x": 12, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "zfs_important_ops{hostname=~\"$hostname\"}",
     "legendFormat": "{{op}}"
    }
   ]
  },
  {
   "title": "ZFS cache hit rate",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 6, "x": 18, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "eps" } },
   "targets": [
    {
     "expr": "zfs_hits_rate{hostname=~\"$hostname\"}",
     "legendFormat": "{{op}}"
    }
   ]
  },
  {
   "title": "Disk - $disk",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 43 },
   "repeat": "disk",
   "collapsed": true,
   "panels": [
    {
     "title": "Disk I/O - $disk",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 6, "x": 0, "y": 44 },
     "fieldConfig": { "defaults": { "unit": "KiBs" } },
     "targets": [
      {
       "expr": "disk_io{hostname=~\"$hostname\", disk=~\"$disk\"}",
       "legendFormat": "{{op}}"
      }
     ]
    },
    {
     "title": "Disk I/O Ops - $disk",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 6, "x": 6, "y": 44 },
     "fieldConfig": { "defaults": { "unit": "iops" } },
     "targets": [
      {
       "expr": "abs(disk_io_ops{hostname=~\"$hostname\", disk=~\"$disk\"})",
       "legendFormat": "{{op}}"
      }
     ]
    },
    {
     "title": "Disk backlog + busy - $disk",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 6, "x": 12, "y": 44 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "disk_io_backlog{hostname=~\"$hostname\", disk=~\"$disk\"}",
       "legendFormat": "backlog"
      },
      {
       "expr": "disk_busy{hostname=~\"$hostname\", disk=~\"$disk\"}",
       "legendFormat": "busy"
      }
     ]
    },
    {
     "title": "Disk utilization - $disk",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 6, "x": 18, "y": 44 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "disk_utilization{hostname=~\"$hostname\", disk=~\"$disk\"}",
       "legendFormat": "utilization"
      }
     ]
    },
    {
     "title": "Disk I/O time - $disk",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 6, "x": 0, "y": 53 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "abs(disk_iotime{hostname=~\"$hostname\", disk=~\"$disk\"})",
       "legendFormat": "{{op}}"
      }
     ]
    },
    {
     "title": "Disk await - $disk",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 6, "x": 6, "y": 53 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "disk_await{hostname=~\"$hostname\", disk=~\"$disk\"}",
       "legendFormat": "{{op}}"
      }
     ]
    },
    {
     "title": "Disk avg I/O size - $disk",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 6, "x": 12, "y": 53 },
     "fieldConfig": { "defaults": { "unit": "kbytes" } },
     "targets": [
      {
       "expr": "abs(disk_io_size{hostname=~\"$hostname\", disk=~\"$disk\"})",
       "legendFormat": "{{op}}"
      }
     ]
    },
    {
     "title": "Disk active operations - $disk",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 6, "x": 18, "y": 53 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "disk_qops{hostname=~\"$hostname\", disk=~\"$disk\"}",
       "legendFormat": "value"
      }
     ]
    }
   ]
  }
 ]
}